/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in source control so `tsc --noEmit` works in fresh CI checkouts.
